#show_downloads: true
title: Bhupesh
masthead_title: "Bhupesh Verma"
logo: "assets/images/logo4.jpg"
description: Computation scientist | Additive Manufacturing

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-include-cache

# Author sidebar content
author:
  name   : "Bhupesh Verma"
  avatar : "/assets/images/avatar.jpg"   # path to your photo
  bio    : "Computation scientist | Additive Manufacturing"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:bhupesh1311@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bhupeshverma/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bhupeshve"
